{% set version = "2.5.0" %}

package:
  name: helper
  version: {{ version }}

source:
  fn: helper-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/helper/helper-{{ version }}.tar.gz
  sha256: 4af39471d25c8820f505bc5c5b1447878bdbec0781c60d73d9ffbdf5383152b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyyaml

test:
  imports:
    - helper

about:
  home: http://helper.readthedocs.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: development library for quickly writing configurable applications and daemons

extra:
  recipe-maintainers:
    - frol
