{% set version = "2.4.2" %}

package:
  name: helper
  version: {{ version }}

source:
  fn: helper-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/helper/helper-{{ version }}.tar.gz
  sha256: a63d4a9255ad5071043e7e4ab8000a512627f1db958b1941b63c7d75e56ea65c

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - pyyaml

test:
  imports:
    - helper

about:
  home: http://helper.readthedocs.org
  license: BSD 3-clause
  summary: development library for quickly writing configurable applications and daemons

extra:
  recipe-maintainers:
    - frol
