travis:
  secure:
    BINSTAR_TOKEN: qHKMvdDiFs3jP54prfJ1PwnRVtWrAw072kLxvuAR4nPR4Uel370hHm9rGvLiqn+wBRZUrH42TGCJbW1WlCsHMJs46BkdZJC4Fcqcrw+Qyug94q/tKH7YQ0oAdUttiKwnuz7qZy1eWx49bypKgCg5XI/XksG5OfdAf6Fpeb141zANrttfJxMZXyPB7Pa88vtcTOliaPGR1tXkr0cUwItpfZ1JsmT5DTC8L9+CJCjGziOgEKD+2ohtUaQM415NBJowzXMs2NyCfROEE1vbHTjlfXc9c/8BYVOrNYUA49hf9S+xfmprlw4Pb1tyIU/jDMZQno4n4yvVl7J7ntb27yHGA/MJQnl0zSUDmmGU+orEYDgQWcELjkLId1S5qZ9aFB1VFXw34j118gD+tHgcJ2EAZNbyhQfgYAPTAe/l8A1W+xQyAjaGWq8NW1mGFwJJJjaDxTMoQqjo8iI8dwPhHeXUGU0baVERYY1Q5vuzf1xjZDoDvK3dn0Vp2JzdVuDrDRXHuCradjbRjOvkFwhGzGFvRd8HJi3u+srYI4H1tUr0LEVUIZAMj7a1yU3oLjOZR9tLX19FUCu4GJEzL9gGuV0okNOJpqh52hNI4Et+gIMBfkbYFTDLhUoRvZAT+cL1gcw7WsBn9qNnf+gZSBLPlJ0ML0Lgi266gE8Z8RG9GwTG6i4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
