travis:
  secure:
    BINSTAR_TOKEN: O0mBwJg3BvR5erZ7G97BEojIKIxzTbiX9FCsZHS2VCvZG5pXP7tKeuUyCNLALDLSyM20Z9TJpjSEFzvgLshP39gmqXQxHdBmREWM092cMmzWw9nn3qnZML3gM3XLTmoXu3cBdpA2PE/eRoUE1TLGZgBZhoPx0x0auqaSt/haC0zsGII5dMxpReDdxTsPN9DwHTuzgwG49pTVU9y+gGfS84vBMKb8nVz2qynkRxXpewlj9BtOeDbuIw5ZYKa0Uho59CR3uyOR3eQ5Ub6WDf7C0krrWW1G75LQd2j98ya236BXEEcS0VLrHrG5GluD0byehp4OCOh1CJTnr0VojKg/K7MjiP6iwcf2zR2QGyvxI45On+YBJiigTKGXOjkZC0IY8idsU4yZYvV3KlCIqe6fSJluiUKj4hCiPB7a+JCCDzyAdYuo4hp1ARBGMAmFCr+CiBogzrAhqDNdnZujciBvzoG2RS6hkF+P7IB8LxKyWp1fAuXRJQvH7k244etjNtrL15w2o60BeFrPxxBbPtA79C5FSHKKWmaApYWmEtYrS50ZvJKkabdtrJvuOPqSu3mBAq/uAaIbm8jzk8cw4SasWl/GY4YJXjMNucEu17QntHLlP78SJQ31tIU44nuGAttwkKGrzSjkul8yHN9sZYHGo0OqAzzBOrAUE/3e7lYy33w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
